### ISSUE TITLE
brew install gcc fails

### ISSUE THREAD

**Issue by mheskett** [greenstick/bootstrapping-package-management-on-exacloud#2] opened 2017-02-19 19:59 UTC
```==> Downloading https://gist.githubusercontent.com/wangpeiwen/60afbacc3e17683865c3b8b8f6448bdb/raw/f383ee29aabe43ae8cc4dfa54e41fd10d02d29c6/glib
Already downloaded: /home/users/heskett/.cache/Homebrew/glibc--patch-c5ffe2ff5237a32621336958eab02ebb1be620939910f83fe8231f39d53e8e6e.patch
==> Patching
==> Applying glibc_ld.so.preload.patch
patch: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by patch)
Error: Failure while executing: patch -g 0 -f -p1 -i /tmp/glibc--patch-20170219-129149-1uv51hq/glibc_ld.so.preload.patch
```

**Comment by greenstick** [comment] 2017-02-19 22:18
It looks like the issue is a missing glibc (version, perhaps); try using Miniconda to install glibc by running the command `conda install -c trung glibc=2.17` and then re-attempting `brew install gcc`.

Let me know if that works and, if not, could you paste the command you ran and any preceding output?

Thanks

**Comment by greenstick** [comment] 2017-02-21 01:14
If anyone else comes across this glibc issue, please let me know. This issue seems to prevent Linuxbrew working for some users; I think I've implemented a workaround on this before but can't remember the details off hand. Leaving this issue open until a fix is found – this issue is being investigated further.

**Comment by erictleung** [comment] 2017-08-04 21:21
This particular issue should be fixed, as I think the cluster should have `GLIBC_2.17` by now.

```bash
$ strings /lib64/libc.so.6 | grep ^GLIBC_2.17 | sort --version-sort
GLIBC_2.2.5
GLIBC_2.2.5
GLIBC_2.2.6
GLIBC_2.2.6
GLIBC_2.3
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.2
GLIBC_2.3.3
GLIBC_2.3.3
GLIBC_2.3.4
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.4
GLIBC_2.5
GLIBC_2.5
GLIBC_2.6
GLIBC_2.6
GLIBC_2.7
GLIBC_2.7
GLIBC_2.8
GLIBC_2.8
GLIBC_2.9
GLIBC_2.9
GLIBC_2.10
GLIBC_2.10
GLIBC_2.11
GLIBC_2.11
GLIBC_2.12
GLIBC_2.12
GLIBC_2.13
GLIBC_2.13
GLIBC_2.14
GLIBC_2.14
GLIBC_2.15
GLIBC_2.15
GLIBC_2.16
GLIBC_2.16
GLIBC_2.17
GLIBC_2.17
```

But if you need a newer version of GLIBC, you might have to find another way.

**Comment by mheskett** [comment] 2017-08-04 21:48
Except now we have migrated to Slurm and a new head node, so many changes
are to come.

**Comment by greenstick** [comment] 2017-11-11 23:33
Recent word is that this issue has been resolved, probably be the recent upgrades to Exacloud. Closing.

**Closed as completed by greenstick** 2017-11-11 23:33 UTC
